### ISSUE TITLE
plz create a new acct

### ISSUE THREAD

**Issue by KS-Hyon** [KS-Hyon/fl-acc#4]

**Comment by KS-Hyon** [comment]
acct name : "bidr0id"
country : Vietnam
plz create a new acct

**Comment by masaokiba** [comment]
how about the existing one?

**Comment by masaokiba** [comment]
Created with the same password. Try login and let me know if you have any other issues.

**Comment by KS-Hyon** [comment]
it's working. good.

**Comment by KS-Hyon** [comment]
but there's no project link.

**Comment by masaokiba** [comment]
awarded, do not accept it.
